In [5]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [6]:
patientinfo = pd.read_csv("PatientInfo.csv")

In [7]:
timeage

           date  time  age  confirmed  deceased
0    2020-03-02     0   0s         32         0
1    2020-03-02     0  10s        169         0
2    2020-03-02     0  20s       1235         0
3    2020-03-02     0  30s        506         1
4    2020-03-02     0  40s        633         1
5    2020-03-02     0  50s        834         5
6    2020-03-02     0  60s        530         6
7    2020-03-02     0  70s        192         6
8    2020-03-02     0  80s         81         3
9    2020-03-03     0   0s         34         0
10   2020-03-03     0  10s        204         0
11   2020-03-03     0  20s       1417         0
12   2020-03-03     0  30s        578         1
13   2020-03-03     0  40s        713         1
14   2020-03-03     0  50s        952         5
15   2020-03-03     0  60s        597         7
16   2020-03-03     0  70s        224         9
17   2020-03-03     0  80s         93         5
18   2020-03-04     0   0s         34         0
19   2020-03-04     0  10s        233         0
20   2020-03-04     0  20s       1575         0
21   2020-03-04     0  30s        631         1
22   2020-03-04     0  40s        790         1
23   2020-03-04     0  50s       1051         5
24   2020-03-04     0  60s        646         7
25   2020-03-04     0  70s        260        12
26   2020-03-04     0  80s        108         6
27   2020-03-05     0   0s         38         0
28   2020-03-05     0  10s        257         0
29   2020-03-05     0  20s       1727         0
..          ...   ...  ...        ...       ...
141  2020-03-17     0  60s       1033        16
142  2020-03-17     0  70s        539        29
143  2020-03-17     0  80s        274        28
144  2020-03-18     0   0s         87         0
145  2020-03-18     0  10s        438         0
146  2020-03-18     0  20s       2342         0
147  2020-03-18     0  30s        873         1
148  2020-03-18     0  40s       1171         1
149  2020-03-18     0  50s       1615         6
150  2020-03-18     0  60s       1059        16
151  2020-03-18     0  70s        542        29
152  2020-03-18     0  80s        286        31
153  2020-03-19     0   0s         91         0
154  2020-03-19     0  10s        444         0
155  2020-03-19     0  20s       2358         0
156  2020-03-19     0  30s        886         1
157  2020-03-19     0  40s       1181         1
158  2020-03-19     0  50s       1642         7
159  2020-03-19     0  60s       1080        17
160  2020-03-19     0  70s        562        34
161  2020-03-19     0  80s        321        31
162  2020-03-20     0   0s         97         0
163  2020-03-20     0  10s        452         0
164  2020-03-20     0  20s       2365         0
165  2020-03-20     0  30s        893         1
166  2020-03-20     0  40s       1193         1
167  2020-03-20     0  50s       1656         7
168  2020-03-20     0  60s       1099        17
169  2020-03-20     0  70s        568        35
170  2020-03-20     0  80s        329        33

[171 rows x 5 columns]

In [8]:
region

,code,province,city,latitude,longitude,elementary_school_count,kindergarten_count,university_count,academy_ratio,elderly_population_ratio,elderly_alone_ratio,nursing_home_count
0,10000,Seoul,Seoul,37.566953,126.977977,607,830,48,1.44,15.38,5.8,22739
1,10010,Seoul,Gangnam-gu,37.518421,127.047222,33,38,0,4.18,13.17,4.3,3088
2,10020,Seoul,Gangdong-gu,37.530492,127.123837,27,32,0,1.54,14.55,5.4,1023
3,10030,Seoul,Gangbuk-gu,37.639938,127.025508,14,21,0,0.67,19.49,8.5,628
4,10040,Seoul,Gangseo-gu,37.551166,126.849506,36,56,1,1.17,14.39,5.7,1080
5,10050,Seoul,Gwanak-gu,37.478290,126.951502,22,33,1,0.89,15.12,4.9,909
6,10060,Seoul,Gwangjin-gu,37.538712,127.082366,22,33,3,1.16,13.75,4.8,723
7,10070,Seoul,Guro-gu,37.495632,126.887650,26,34,3,1.00,16.21,5.7,741
8,10080,Seoul,Geumcheon-gu,37.456852,126.895229,18,19,0,0.96,16.15,6.7,475
9,10090,Seoul,Nowon-gu,37.654259,127.056294,42,66,6,1.39,15.40,7.4,952
10,10100,Seoul,Dobong-gu,37.668952,127.047082,23,26,1,0.95,17.89,7.2,485
11,10110,Seoul,Dongdaemun-gu,37.574552,127.039721,21,31,4,1.06,17.26,6.7,832
12,10120,Seoul,Dongjak-gu,37.510571,126.963604,21,34,3,1.17,15.85,5.2,762
13,10130,Seoul,Mapo-gu,37.566283,126.901644,22,24,2,1.83,14.05,4.9,929
14,10140,Seoul,Seodaemun-gu,37.579428,126.936771,19,25,6,1.12,16.77,6.2,587
15,10150,Seoul,Seocho-gu,37.483804,127.032693,24,27,1,2.60,13.39,3.8,1465
16,10160,Seoul,Seongdong-gu,37.563277,127.036647,21,30,2,0.97,14.76,5.3,593
17,10170,Seoul,Seongbuk-gu,37.589562,127.016700,29,49,6,1.02,16.15,6.0,729
18,10180,Seoul,Songpa-gu,37.514620,127.106141,40,51,1,1.65,13.10,4.1,1527
19,10190,Seoul,Yangcheon-gu,37.517189,126.866618,30,43,0,2.26,13.55,5.5,816
20,10200,Seoul,Yeongdeungpo-gu,37.526505,126.896190,23,39,0,1.21,15.60,5.8,1001
21,10210,Seoul,Yongsan-gu,37.532768,126.990021,15,13,1,0.68,16.87,6.5,435
22,10220,Seoul,Eunpyeong-gu,37.603481,126.929173,31,44,1,1.09,17.00,6.5,874
23,10230,Seoul,Jongno-gu,37.572999,126.979189,13,17,3,1.71,18.27,6.8,668
24,10240,Seoul,Jung-gu,37.563988,126.997530,12,14,2,0.94,18.42,7.4,728
25,10250,Seoul,Jungnang-gu,37.606832,127.092656,23,31,1,0.70,16.65,6.9,689
26,11000,Busan,Busan,35.179884,129.074796,304,408,22,1.40,18.41,8.6,6752
27,11010,Busan,Gangseo-gu,35.212424,128.980680,17,21,0,1.43,11.84,5.0,147
28,11020,Busan,Geumjeong-gu,35.243053,129.092163,22,28,4,1.64,19.80,8.4,466
29,11030,Busan,Gijang-gun,35.244881,129.222253,21,35,0,1.31,15.45,7.4,229
...,...,...,...,...,...,...,...,...,...,...,...,...
214,60150,Gyeongsangbuk-do,Yeongcheon-si,35.973268,128.938603,18,23,1,0.83,27.32,15.3,192
215,60160,Gyeongsangbuk-do,Yecheon-gun,36.646707,128.437435,12,15,1,1.09,29.79,18.4,97
216,60170,Gyeongsangbuk-do,Ulleung-gun,37.484438,130.905883,4,6,0,0.21,24.81,10.7,11
217,60180,Gyeongsangbuk-do,Uljin-gun,36.993078,129.400585,13,16,0,1.01,27.30,17.6,83
218,60190,Gyeongsangbuk-do,Uiseong-gun,36.352718,128.697088,16,16,0,0.32,40.26,23.7,108
219,60200,Gyeongsangbuk-do,Cheongdo-gun,35.647361,128.734382,11,14,0,0.63,36.55,21.0,85
220,60210,Gyeongsangbuk-do,Cheongsong-gun,36.436301,129.057080,8,8,0,0.51,36.08,19.4,55
221,60220,Gyeongsangbuk-do,Chilgok-gun,35.995529,128.401735,21,32,2,1.48,15.17,6.7,151
222,60230,Gyeongsangbuk-do,Pohang-si,36.019052,129.343645,66,117,4,1.51,16.44,8.0,877
223,61000,Gyeongsangnam-do,Gyeongsangnam-do,35.238294,128.692397,501,686,21,1.78,16.51,9.1,5364
224,61010,Gyeongsangnam-do,Geoje-si,34.880519,128.621216,38,58,1,1.76,10.22,4.7,317
225,61020,Gyeongsangnam-do,Geochang-gun,35.686526,127.910021,17,16,2,1.25,27.01,17.4,127
226,61030,Gyeongsangnam-do,Goseong-gun,34.972986,128.322246,19,18,0,1.30,30.17,18.2,89
227,61040,Gyeongsangnam-do,Gimhae-si,35.228678,128.889352,58,91,4,2.10,10.74,5.3,711
228,61050,Gyeongsangnam-do,Namhae-gun,34.837688,127.892595,13,10,1,1.03,36.92,23.3,88
229,61060,Gyeongsangnam-do,Miryang-si,35.503827,128.746604,21,25,0,1.39,27.31,16.3,178
230,61070,Gyeongsangnam-do,Sacheon-si,35.003668,128.064272,18,20,0,1.84,21.17,11.7,191
231,61080,Gyeongsangnam-do,Sancheong-gun,35.415544,127.873490,13,11,0,0.65,35.42,20.6,72
232,61090,Gyeongsangnam-do,Yangsan-si,35.335016,129.037057,37,68,2,1.59,12.92,6.2,507
233,61100,Gyeongsangnam-do,Uiryeong-gun,35.322198,128.261740,13,10,0,0.63,35.95,24.2,60
234,61110,Gyeongsangnam-do,Jinju-si,35.180313,128.108750,45,53,6,2.49,16.27,8.6,597
235,61120,Gyeongsangnam-do,Changnyeong-gun,35.544603,128.492330,17,20,0,0.80,29.80,18.4,129
236,61130,Gyeongsangnam-do,Changwon-si,35.227992,128.681815,110,195,5,1.84,13.64,6.5,1701
237,61140,Gyeongsangnam-do,Tongyeong-si,34.854426,128.433210,20,29,0,1.70,18.47,9.8,230
238,61150,Gyeongsangnam-do,Hadong-gun,35.067224,127.751271,16,15,0,0.84,32.89,19.1,94
239,61160,Gyeongsangnam-do,Haman-gun,35.272481,128.406540,16,20,0,1.19,23.74,14.7,94
240,61170,Gyeongsangnam-do,Hamyang-gun,35.520541,127.725177,13,12,0,1.01,32.65,20.9,83
241,61180,Gyeongsangnam-do,Hapcheon-gun,35.566702,128.165870,17,15,0,0.71,38.44,24.7,96
242,70000,Jeju-do,Jeju-do,33.488936,126.500423,113,123,4,1.53,15.10,6.4,1245
243,80000,Korea,Korea,37.566953,126.977977,6087,8837,340,1.56,15.67,7.2,94865

In [9]:
time

          date  time    test  negative  confirmed  released  deceased
0   2020-01-20    16       1         0          1         0         0
1   2020-01-21    16       1         0          1         0         0
2   2020-01-22    16       4         3          1         0         0
3   2020-01-23    16      22        21          1         0         0
4   2020-01-24    16      27        25          2         0         0
5   2020-01-25    16      27        25          2         0         0
6   2020-01-26    16      51        47          3         0         0
7   2020-01-27    16      61        56          4         0         0
8   2020-01-28    16     116        97          4         0         0
9   2020-01-29    16     187       155          4         0         0
10  2020-01-30    16     246       199          6         0         0
11  2020-01-31    16     312       245         11         0         0
12  2020-02-01    16     371       289         12         0         0
13  2020-02-02    16     429       327         15         0         0
14  2020-02-03    16     490       414         15         0         0
15  2020-02-04    16     607       462         16         0         0
16  2020-02-05    16     714       522         18         1         0
17  2020-02-06    16     885       693         23         2         0
18  2020-02-07    16    1352      1001         24         2         0
19  2020-02-08    16    2097      1134         24         2         0
20  2020-02-09    16    2598      1683         27         3         0
21  2020-02-10    16    3110      2552         27         4         0
22  2020-02-11    16    4325      3535         28         4         0
23  2020-02-12    16    5624      4811         28         7         0
24  2020-02-13    16    6511      5921         28         7         0
25  2020-02-14    16    7242      6679         28         7         0
26  2020-02-15    16    7734      7148         28         9         0
27  2020-02-16    16    8161      7647         29         9         0
28  2020-02-17    16    8718      7980         30        10         0
29  2020-02-18    16    9772      8923         31        12         0
..         ...   ...     ...       ...        ...       ...       ...
31  2020-02-20    16   13202     11238        104        16         1
32  2020-02-21    16   16400     13016        204        17         2
33  2020-02-22    16   21586     15116        433        18         2
34  2020-02-23    16   26179     17520        602        18         6
35  2020-02-24    16   32756     20292        833        24         8
36  2020-02-25    16   40304     25447        977        24        12
37  2020-02-26    16   53553     31576       1261        24        12
38  2020-02-27    16   66652     39318       1766        26        13
39  2020-02-28    16   81167     48593       2337        27        13
40  2020-02-29    16   94055     55723       3150        28        17
41  2020-03-01    16   98921     61825       3736        30        18
42  2020-03-02     0  109591     71580       4212        31        22
43  2020-03-03     0  125851     85484       4812        34        28
44  2020-03-04     0  136707    102965       5328        41        32
45  2020-03-05     0  146541    118965       5766        88        35
46  2020-03-06     0  164740    136624       6284       108        42
47  2020-03-07     0  178189    151802       6767       118        44
48  2020-03-08     0  188518    162008       7134       130        50
49  2020-03-09     0  196618    171778       7382       166        51
50  2020-03-10     0  210144    184179       7513       247        54
51  2020-03-11     0  222395    196100       7755       288        60
52  2020-03-12     0  234998    209402       7869       333        66
53  2020-03-13     0  248647    222728       7979       510        67
54  2020-03-14     0  261335    235615       8086       714        72
55  2020-03-15     0  268212    243778       8126       834        75
56  2020-03-16     0  274504    251297       8236      1137        75
57  2020-03-17     0  286716    261105       8320      1401        81
58  2020-03-18     0  295647    270888       8413      1540        84
59  2020-03-19     0  307024    282555       8565      1947        91
60  2020-03-20     0  316664    292487       8652      2233        94

[61 rows x 7 columns]

In [12]:
patientinfo

,patient_id,global_num,sex,birth_year,age,country,province,city,disease,infection_case,infection_order,infected_by,contact_number,symptom_onset_date,confirmed_date,released_date,deceased_date,state
0,1000000001,2.0,male,1964.0,50s,Korea,Seoul,Gangseo-gu,NaN,overseas inflow,1.0,NaN,75.0,2020-01-22,2020-01-23,2020-02-05,NaN,released
1,1000000002,5.0,male,1987.0,30s,Korea,Seoul,Jungnang-gu,NaN,overseas inflow,1.0,NaN,31.0,NaN,2020-01-30,2020-03-02,NaN,released
2,1000000003,6.0,male,1964.0,50s,Korea,Seoul,Jongno-gu,NaN,contact with patient,2.0,2.002000e+09,17.0,NaN,2020-01-30,2020-02-19,NaN,released
3,1000000004,7.0,male,1991.0,20s,Korea,Seoul,Mapo-gu,NaN,overseas inflow,1.0,NaN,9.0,2020-01-26,2020-01-30,2020-02-15,NaN,released
4,1000000005,9.0,female,1992.0,20s,Korea,Seoul,Seongbuk-gu,NaN,contact with patient,2.0,1.000000e+09,2.0,NaN,2020-01-31,2020-02-24,NaN,released
5,1000000006,10.0,female,1966.0,50s,Korea,Seoul,Jongno-gu,NaN,contact with patient,3.0,1.000000e+09,43.0,NaN,2020-01-31,2020-02-19,NaN,released
6,1000000007,11.0,male,1995.0,20s,Korea,Seoul,Jongno-gu,NaN,contact with patient,3.0,1.000000e+09,0.0,NaN,2020-01-31,2020-02-10,NaN,released
7,1000000008,13.0,male,1992.0,20s,Korea,Seoul,etc,NaN,overseas inflow,1.0,NaN,0.0,NaN,2020-02-02,2020-02-24,NaN,released
8,1000000009,19.0,male,1983.0,30s,Korea,Seoul,Songpa-gu,NaN,overseas inflow,2.0,NaN,68.0,NaN,2020-02-05,2020-02-21,NaN,released
9,1000000010,21.0,female,1960.0,60s,Korea,Seoul,Seongbuk-gu,NaN,contact with patient,3.0,1.000000e+09,6.0,NaN,2020-02-05,2020-02-29,NaN,released
10,1000000011,23.0,female,1962.0,50s,China,Seoul,Seodaemun-gu,NaN,overseas inflow,1.0,NaN,23.0,NaN,2020-02-06,2020-02-29,NaN,released
11,1000000012,24.0,male,1992.0,20s,Korea,Seoul,etc,NaN,overseas inflow,1.0,NaN,0.0,NaN,2020-02-07,2020-02-27,NaN,released
12,1000000013,29.0,male,1938.0,80s,Korea,Seoul,Jongno-gu,NaN,contact with patient,4.0,1.000000e+09,117.0,NaN,2020-02-16,NaN,NaN,released
13,1000000014,30.0,female,1952.0,60s,Korea,Seoul,Jongno-gu,NaN,contact with patient,5.0,1.000000e+09,27.0,2020-02-06,2020-02-16,2020-03-12,NaN,released
14,1000000015,40.0,male,1943.0,70s,Korea,Seoul,Seongdong-gu,NaN,Seongdong-gu APT,NaN,NaN,8.0,2020-02-11,2020-02-19,NaN,NaN,isolated
15,1000000016,56.0,male,1945.0,70s,Korea,Seoul,Jongno-gu,NaN,contact with patient,4.0,1.000000e+09,NaN,NaN,2020-02-19,2020-03-11,NaN,released
16,1000000017,83.0,male,1944.0,70s,Korea,Seoul,Jongno-gu,NaN,contact with patient,3.0,1.000000e+09,NaN,NaN,2020-02-20,2020-03-01,NaN,released
17,1000000018,111.0,male,2000.0,20s,Korea,Seoul,etc,NaN,etc,NaN,NaN,NaN,NaN,2020-02-20,NaN,NaN,isolated
18,1000000019,112.0,female,1941.0,70s,Korea,Seoul,Jongno-gu,NaN,contact with patient,5.0,1.000000e+09,NaN,NaN,2020-02-20,2020-03-08,NaN,released
19,1000000020,121.0,female,1944.0,70s,Korea,Seoul,Seongdong-gu,NaN,Seongdong-gu APT,NaN,1.000000e+09,NaN,NaN,2020-02-20,NaN,NaN,isolated
20,1000000021,136.0,male,1936.0,80s,Korea,Seoul,Jongno-gu,NaN,contact with patient,5.0,1.000000e+09,NaN,NaN,2020-02-20,2020-03-08,NaN,released
21,1000000022,161.0,male,1985.0,30s,Korea,Seoul,Seodaemun-gu,NaN,Eunpyeong St. Mary's Hospital,NaN,NaN,NaN,NaN,2020-02-21,NaN,NaN,isolated
22,1000000023,188.0,male,1961.0,50s,Korea,Seoul,Seocho-gu,NaN,Shincheonji Church,NaN,NaN,NaN,NaN,2020-02-21,NaN,NaN,isolated
23,1000000024,348.0,male,1980.0,40s,Korea,Seoul,Guro-gu,NaN,contact with patient,NaN,NaN,NaN,NaN,2020-02-22,2020-03-14,NaN,released
24,1000000025,365.0,male,1958.0,60s,Korea,Seoul,Gangdong-gu,NaN,Eunpyeong St. Mary's Hospital,NaN,1.000000e+09,NaN,NaN,2020-02-22,NaN,NaN,isolated
25,1000000026,420.0,male,1986.0,30s,Korea,Seoul,Seocho-gu,NaN,etc,NaN,NaN,NaN,2020-02-21,2020-02-22,2020-03-11,NaN,released
26,1000000027,593.0,male,1968.0,50s,Korea,Seoul,Gangseo-gu,NaN,overseas inflow,NaN,NaN,NaN,NaN,2020-02-23,2020-03-04,NaN,released
27,1000000028,627.0,female,1950.0,70s,Korea,Seoul,Jongno-gu,NaN,Eunpyeong St. Mary's Hospital,NaN,NaN,NaN,NaN,2020-02-23,2020-03-11,NaN,released
28,1000000029,754.0,female,1995.0,20s,Korea,Seoul,Jongno-gu,NaN,Eunpyeong St. Mary's Hospital,NaN,1.000000e+09,NaN,2020-02-11,2020-02-26,2020-03-11,NaN,released
29,1000000030,755.0,male,1954.0,60s,China,Seoul,Gangdong-gu,NaN,Eunpyeong St. Mary's Hospital,NaN,NaN,NaN,NaN,2020-02-23,NaN,NaN,released
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2188,6104000060,NaN,male,1966.0,50s,Korea,Gyeongsangnam-do,Gimhae-si,NaN,NaN,NaN,NaN,NaN,NaN,2020-02-28,NaN,NaN,isolated
2189,6112000061,NaN,male,1990.0,30s,Korea,Gyeongsangnam-do,Changnyeong-gun,NaN,NaN,NaN,NaN,NaN,NaN,2020-02-29,NaN,NaN,isolated
2190,6113000062,NaN,female,1999.0,20s,Korea,Gyeongsangnam-do,Changwon-si,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-01,NaN,NaN,released
2191,6103000063,NaN,female,2000.0,20s,Korea,Gyeongsangnam-do,Goseong-gun,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-01,NaN,NaN,isolated
2192,6102000064,NaN,female,1999.0,20s,Korea,Gyeongsangnam-do,Geochang-gun,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-02,NaN,NaN,released
2193,6101000065,NaN,female,1962.0,50s,Korea,Gyeongsangnam-do,Geoje-si,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-03,NaN,NaN,isolated
2194,6102000066,NaN,female,1958.0,60s,Korea,Gyeongsangnam-do,Geochang-gun,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-03,NaN,NaN,isolated
2195,6102000067,NaN,male,1960.0,60s,Korea,Gyeongsangnam-do,Geochang-gun,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-04,NaN,NaN,isolated
2196,6102000068,NaN,female,1957.0,60s,Korea,Gyeongsangnam-do,Geochang-gun,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-04,NaN,NaN,isolated
2197,6102000069,NaN,female,1960.0,60s,Korea,Gyeongsangnam-do,Geochang-gun,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-04,NaN,NaN,isolated
2198,6100000070,NaN,male,1996.0,20s,Korea,Gyeongsangnam-do,Changnyeong-gun,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-04,NaN,NaN,released
2199,6112000071,NaN,female,2004.0,10s,Korea,Gyeongsangnam-do,Changnyeong-gun,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-04,NaN,NaN,isolated
2200,6112000072,NaN,female,1954.0,60s,Korea,Gyeongsangnam-do,Changnyeong-gun,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-04,NaN,NaN,isolated
2201,6106000073,NaN,male,1957.0,60s,Korea,Gyeongsangnam-do,Miryang-si,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-04,NaN,NaN,isolated
2202,6113000074,NaN,female,1983.0,30s,Korea,Gyeongsangnam-do,Changwon-si,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-04,NaN,NaN,isolated
2203,6113000075,NaN,male,2014.0,0s,Korea,Gyeongsangnam-do,Changwon-si,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-05,NaN,NaN,released
2204,6112000076,NaN,male,1996.0,20s,Korea,Gyeongsangnam-do,Changnyeong-gun,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-05,NaN,NaN,isolated
2205,6102000077,NaN,female,1944.0,70s,Korea,Gyeongsangnam-do,Geochang-gun,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-05,NaN,NaN,isolated
2206,6113000078,NaN,female,1975.0,40s,Korea,Gyeongsangnam-do,Changwon-si,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-05,NaN,NaN,isolated
2207,6112000079,NaN,male,1994.0,20s,Korea,Gyeongsangnam-do,Changnyeong-gun,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-06,NaN,NaN,isolated
2208,6102000080,NaN,female,1969.0,50s,Korea,Gyeongsangnam-do,Geochang-gun,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-06,NaN,NaN,released
2209,6102000081,NaN,female,1947.0,70s,Korea,Gyeongsangnam-do,Geochang-gun,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-06,NaN,NaN,isolated
2210,6102000082,NaN,male,1963.0,50s,Korea,Gyeongsangnam-do,Geochang-gun,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-07,NaN,NaN,released
2211,6101000083,NaN,male,1992.0,20s,Korea,Gyeongsangnam-do,Geoje-si,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-10,NaN,NaN,released
2212,6101000084,NaN,male,1971.0,40s,Korea,Gyeongsangnam-do,Geoje-si,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-11,NaN,NaN,isolated
2213,6100000085,NaN,male,1990.0,30s,Korea,Gyeongsangnam-do,Changwon-si,NaN,NaN,NaN,NaN,NaN,NaN,2020-03-16,NaN,NaN,NaN
2214,7000000001,139.0,male,1998.0,20s,Korea,Jeju-do,Jeju-do,NaN,etc,NaN,NaN,87.0,NaN,2020-02-20,NaN,NaN,isolated
2215,7000000002,222.0,female,1998.0,20s,Korea,Jeju-do,Jeju-do,NaN,etc,NaN,NaN,84.0,NaN,2020-02-22,2020-03-07,NaN,released
2216,7000000003,4345.0,female,1972.0,40s,Korea,Jeju-do,etc,NaN,etc,NaN,NaN,21.0,NaN,2020-03-02,2020-03-15,NaN,released
2217,7000000004,5534.0,male,1974.0,40s,Korea,Jeju-do,Jeju-do,NaN,etc,NaN,NaN,74.0,NaN,2020-03-04,NaN,NaN,isolated

In [193]:
patientinfo.dropna(subset=['age'],inplace=True)
patientinfo.age.isnull().any()
needed = patientinfo[['sex','age']]
needed['age'] = needed['age'].apply(lambda x: int(x.strip('s')))
male = needed[needed['sex'] == 'male']
female = needed[needed['sex'] == 'female']
male = male.groupby("age").count().reset_index().rename(columns={"sex": "count"})
male["sex"] = 'male'
#male['age'] = male['age'].apply(lambda x: int(x.strip('s')))
female = female.groupby("age").count().reset_index().rename(columns={"sex": "count"})
female["sex"] = 'female'
final = pd.concat([male,female]).reset_index()[['age','count','sex']]
final

C:\Users\j3543\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

    age  count     sex
0     0     18    male
1    10     43    male
2    20    225    male
3    30    126    male
4    40    109    male
5    50    148    male
6    60    105    male
7    70     46    male
8    80     29    male
9    90      4    male
10    0     11  female
11   10     31  female
12   20    240  female
13   30    125  female
14   40    194  female
15   50    237  female
16   60    124  female
17   70     71  female
18   80     55  female
19   90     13  female
20  100      1  female